//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innovt.Contrib.Authorization.Platform {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Innovt.Contrib.Authorization.Platform.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GroupAlreadyExist {
            get {
                return ResourceManager.GetString("GroupAlreadyExist", resourceCulture);
            }
        }
        
        internal static string GroupNotFound {
            get {
                return ResourceManager.GetString("GroupNotFound", resourceCulture);
            }
        }
        
        internal static string InvalidUserOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserOrPassword", resourceCulture);
            }
        }
        
        internal static string PermissionAlreadyExist {
            get {
                return ResourceManager.GetString("PermissionAlreadyExist", resourceCulture);
            }
        }
        
        internal static string PermissionNotFound {
            get {
                return ResourceManager.GetString("PermissionNotFound", resourceCulture);
            }
        }
        
        internal static string RoleAlreadyExist {
            get {
                return ResourceManager.GetString("RoleAlreadyExist", resourceCulture);
            }
        }
        
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
    }
}
