//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innovt.Cloud.AWS.Cognito.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Innovt.Cloud.AWS.Cognito.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessTokenIsRequired.
        /// </summary>
        internal static string AccessTokenIsRequired {
            get {
                return ResourceManager.GetString("AccessTokenIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttributesIsRequired.
        /// </summary>
        internal static string AttributesIsRequired {
            get {
                return ResourceManager.GetString("AttributesIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChallengeNameIsRequired.
        /// </summary>
        internal static string ChallengeNameIsRequired {
            get {
                return ResourceManager.GetString("ChallengeNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChallengeNotAvailable.
        /// </summary>
        internal static string ChallengeNotAvailable {
            get {
                return ResourceManager.GetString("ChallengeNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeMismatch.
        /// </summary>
        internal static string CodeMismatch {
            get {
                return ResourceManager.GetString("CodeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmationCodeRequired.
        /// </summary>
        internal static string ConfirmationCodeRequired {
            get {
                return ResourceManager.GetString("ConfirmationCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPasswordIsRequired.
        /// </summary>
        internal static string ConfirmPasswordIsRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentPasswordRequired.
        /// </summary>
        internal static string CurrentPasswordRequired {
            get {
                return ResourceManager.GetString("CurrentPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentAlreadyBeenUsed.
        /// </summary>
        internal static string DocumentAlreadyBeenUsed {
            get {
                return ResourceManager.GetString("DocumentAlreadyBeenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentIsRequired.
        /// </summary>
        internal static string DocumentIsRequired {
            get {
                return ResourceManager.GetString("DocumentIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailIsRequired.
        /// </summary>
        internal static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiredCode.
        /// </summary>
        internal static string ExpiredCode {
            get {
                return ResourceManager.GetString("ExpiredCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldFilterIsRequired.
        /// </summary>
        internal static string FieldFilterIsRequired {
            get {
                return ResourceManager.GetString("FieldFilterIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstNameIsRequired.
        /// </summary>
        internal static string FirstNameIsRequired {
            get {
                return ResourceManager.GetString("FirstNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelloWorld.
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalServerError.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidChallenge.
        /// </summary>
        internal static string InvalidChallenge {
            get {
                return ResourceManager.GetString("InvalidChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidChallengeSession.
        /// </summary>
        internal static string InvalidChallengeSession {
            get {
                return ResourceManager.GetString("InvalidChallengeSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidCountryCode.
        /// </summary>
        internal static string InvalidCountryCode {
            get {
                return ResourceManager.GetString("InvalidCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidDocument.
        /// </summary>
        internal static string InvalidDocument {
            get {
                return ResourceManager.GetString("InvalidDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidGender.
        /// </summary>
        internal static string InvalidGender {
            get {
                return ResourceManager.GetString("InvalidGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidPassword.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidPhone.
        /// </summary>
        internal static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidSocialProvider.
        /// </summary>
        internal static string InvalidSocialProvider {
            get {
                return ResourceManager.GetString("InvalidSocialProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidUserName.
        /// </summary>
        internal static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidUserOrPassword.
        /// </summary>
        internal static string InvalidUserOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpAddressRequired.
        /// </summary>
        internal static string IpAddressRequired {
            get {
                return ResourceManager.GetString("IpAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastNameIsRequired.
        /// </summary>
        internal static string LastNameIsRequired {
            get {
                return ResourceManager.GetString("LastNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LimitExceeded.
        /// </summary>
        internal static string LimitExceeded {
            get {
                return ResourceManager.GetString("LimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotAuthorized.
        /// </summary>
        internal static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuthCodeNotFound.
        /// </summary>
        internal static string OAuthCodeNotFound {
            get {
                return ResourceManager.GetString("OAuthCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuthProviderNotFound.
        /// </summary>
        internal static string OAuthProviderNotFound {
            get {
                return ResourceManager.GetString("OAuthProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordResetRequired.
        /// </summary>
        internal static string PasswordResetRequired {
            get {
                return ResourceManager.GetString("PasswordResetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordsDoNotMatch.
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneIsRequired.
        /// </summary>
        internal static string PhoneIsRequired {
            get {
                return ResourceManager.GetString("PhoneIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedirectUriRequired.
        /// </summary>
        internal static string RedirectUriRequired {
            get {
                return ResourceManager.GetString("RedirectUriRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshTokenIsRequired.
        /// </summary>
        internal static string RefreshTokenIsRequired {
            get {
                return ResourceManager.GetString("RefreshTokenIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireUpdateProfile.
        /// </summary>
        internal static string RequireUpdateProfile {
            get {
                return ResourceManager.GetString("RequireUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerNameRequired.
        /// </summary>
        internal static string ServerNameRequired {
            get {
                return ResourceManager.GetString("ServerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerPathRequired.
        /// </summary>
        internal static string ServerPathRequired {
            get {
                return ResourceManager.GetString("ServerPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocialLoginError.
        /// </summary>
        internal static string SocialLoginError {
            get {
                return ResourceManager.GetString("SocialLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TooManyRequests.
        /// </summary>
        internal static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsernameAlreadyExists.
        /// </summary>
        internal static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNameIsRequired.
        /// </summary>
        internal static string UserNameIsRequired {
            get {
                return ResourceManager.GetString("UserNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotConfirmed.
        /// </summary>
        internal static string UserNotConfirmed {
            get {
                return ResourceManager.GetString("UserNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotFound.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotFoundAfterCodeConfirmation.
        /// </summary>
        internal static string UserNotFoundAfterCodeConfirmation {
            get {
                return ResourceManager.GetString("UserNotFoundAfterCodeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserSocialNotFound.
        /// </summary>
        internal static string UserSocialNotFound {
            get {
                return ResourceManager.GetString("UserSocialNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueFieldIsRequired.
        /// </summary>
        internal static string ValueFieldIsRequired {
            get {
                return ResourceManager.GetString("ValueFieldIsRequired", resourceCulture);
            }
        }
    }
}
