### YamlMime:ManagedReference
items:
- uid: Innovt.Core.Security
  commentId: N:Innovt.Core.Security
  id: Innovt.Core.Security
  children:
  - Innovt.Core.Security.IBasicAuthService
  langs:
  - csharp
  - vb
  name: Innovt.Core.Security
  nameWithType: Innovt.Core.Security
  fullName: Innovt.Core.Security
  type: Namespace
  assemblies:
  - Innovt.Core
references:
- uid: Innovt.Core.Security.IBasicAuthService
  commentId: T:Innovt.Core.Security.IBasicAuthService
  parent: Innovt.Core.Security
  href: Innovt.Core.Security.IBasicAuthService.html
  name: IBasicAuthService
  nameWithType: IBasicAuthService
  fullName: Innovt.Core.Security.IBasicAuthService
- uid: Innovt.Core.Security
  commentId: N:Innovt.Core.Security
  href: Innovt.html
  name: Innovt.Core.Security
  nameWithType: Innovt.Core.Security
  fullName: Innovt.Core.Security
  spec.csharp:
  - uid: Innovt
    name: Innovt
    href: Innovt.html
  - name: .
  - uid: Innovt.Core
    name: Core
    href: Innovt.Core.html
  - name: .
  - uid: Innovt.Core.Security
    name: Security
    href: Innovt.Core.Security.html
  spec.vb:
  - uid: Innovt
    name: Innovt
    href: Innovt.html
  - name: .
  - uid: Innovt.Core
    name: Core
    href: Innovt.Core.html
  - name: .
  - uid: Innovt.Core.Security
    name: Security
    href: Innovt.Core.Security.html
