### YamlMime:ManagedReference
items:
- uid: Innovt.Domain.Security
  commentId: N:Innovt.Domain.Security
  id: Innovt.Domain.Security
  children:
  - Innovt.Domain.Security.AuthUser
  - Innovt.Domain.Security.BasicAuthCredentials
  - Innovt.Domain.Security.Group
  - Innovt.Domain.Security.IAuthorizationRepository
  - Innovt.Domain.Security.Permission
  - Innovt.Domain.Security.Role
  langs:
  - csharp
  - vb
  name: Innovt.Domain.Security
  nameWithType: Innovt.Domain.Security
  fullName: Innovt.Domain.Security
  type: Namespace
  assemblies:
  - Innovt.Domain
references:
- uid: Innovt.Domain.Security.AuthUser
  commentId: T:Innovt.Domain.Security.AuthUser
  href: Innovt.Domain.Security.AuthUser.html
  name: AuthUser
  nameWithType: AuthUser
  fullName: Innovt.Domain.Security.AuthUser
- uid: Innovt.Domain.Security.BasicAuthCredentials
  commentId: T:Innovt.Domain.Security.BasicAuthCredentials
  href: Innovt.Domain.Security.BasicAuthCredentials.html
  name: BasicAuthCredentials
  nameWithType: BasicAuthCredentials
  fullName: Innovt.Domain.Security.BasicAuthCredentials
- uid: Innovt.Domain.Security.Group
  commentId: T:Innovt.Domain.Security.Group
  parent: Innovt.Domain.Security
  href: Innovt.Domain.Security.Group.html
  name: Group
  nameWithType: Group
  fullName: Innovt.Domain.Security.Group
- uid: Innovt.Domain.Security.IAuthorizationRepository
  commentId: T:Innovt.Domain.Security.IAuthorizationRepository
  parent: Innovt.Domain.Security
  href: Innovt.Domain.Security.IAuthorizationRepository.html
  name: IAuthorizationRepository
  nameWithType: IAuthorizationRepository
  fullName: Innovt.Domain.Security.IAuthorizationRepository
- uid: Innovt.Domain.Security.Permission
  commentId: T:Innovt.Domain.Security.Permission
  parent: Innovt.Domain.Security
  href: Innovt.Domain.Security.Permission.html
  name: Permission
  nameWithType: Permission
  fullName: Innovt.Domain.Security.Permission
- uid: Innovt.Domain.Security.Role
  commentId: T:Innovt.Domain.Security.Role
  parent: Innovt.Domain.Security
  href: Innovt.Domain.Security.Role.html
  name: Role
  nameWithType: Role
  fullName: Innovt.Domain.Security.Role
- uid: Innovt.Domain.Security
  commentId: N:Innovt.Domain.Security
  href: Innovt.html
  name: Innovt.Domain.Security
  nameWithType: Innovt.Domain.Security
  fullName: Innovt.Domain.Security
  spec.csharp:
  - uid: Innovt
    name: Innovt
    href: Innovt.html
  - name: .
  - uid: Innovt.Domain
    name: Domain
    href: Innovt.Domain.html
  - name: .
  - uid: Innovt.Domain.Security
    name: Security
    href: Innovt.Domain.Security.html
  spec.vb:
  - uid: Innovt
    name: Innovt
    href: Innovt.html
  - name: .
  - uid: Innovt.Domain
    name: Domain
    href: Innovt.Domain.html
  - name: .
  - uid: Innovt.Domain.Security
    name: Security
    href: Innovt.Domain.Security.html
