### YamlMime:ManagedReference
items:
- uid: Innovt.AspNetCore.Application.Tests
  commentId: N:Innovt.AspNetCore.Application.Tests
  id: Innovt.AspNetCore.Application.Tests
  children:
  - Innovt.AspNetCore.Application.Tests.Program
  - Innovt.AspNetCore.Application.Tests.Startup
  langs:
  - csharp
  - vb
  name: Innovt.AspNetCore.Application.Tests
  nameWithType: Innovt.AspNetCore.Application.Tests
  fullName: Innovt.AspNetCore.Application.Tests
  type: Namespace
  assemblies:
  - Innovt.AspNetCore.Application.Tests
references:
- uid: Innovt.AspNetCore.Application.Tests.Program
  commentId: T:Innovt.AspNetCore.Application.Tests.Program
  href: Innovt.AspNetCore.Application.Tests.Program.html
  name: Program
  nameWithType: Program
  fullName: Innovt.AspNetCore.Application.Tests.Program
- uid: Innovt.AspNetCore.Application.Tests.Startup
  commentId: T:Innovt.AspNetCore.Application.Tests.Startup
  href: Innovt.AspNetCore.Application.Tests.Startup.html
  name: Startup
  nameWithType: Startup
  fullName: Innovt.AspNetCore.Application.Tests.Startup
