### YamlMime:ManagedReference
items:
- uid: Innovt.Cloud.AWS.Configuration
  commentId: N:Innovt.Cloud.AWS.Configuration
  id: Innovt.Cloud.AWS.Configuration
  children:
  - Innovt.Cloud.AWS.Configuration.AssumeRoleAwsConfiguration
  - Innovt.Cloud.AWS.Configuration.DefaultAwsConfiguration
  - Innovt.Cloud.AWS.Configuration.IAssumeRoleAwsConfiguration
  - Innovt.Cloud.AWS.Configuration.IAwsConfiguration
  langs:
  - csharp
  - vb
  name: Innovt.Cloud.AWS.Configuration
  nameWithType: Innovt.Cloud.AWS.Configuration
  fullName: Innovt.Cloud.AWS.Configuration
  type: Namespace
  assemblies:
  - Innovt.Cloud.AWS
references:
- uid: Innovt.Cloud.AWS.Configuration.AssumeRoleAwsConfiguration
  commentId: T:Innovt.Cloud.AWS.Configuration.AssumeRoleAwsConfiguration
  href: Innovt.Cloud.AWS.Configuration.AssumeRoleAwsConfiguration.html
  name: AssumeRoleAwsConfiguration
  nameWithType: AssumeRoleAwsConfiguration
  fullName: Innovt.Cloud.AWS.Configuration.AssumeRoleAwsConfiguration
- uid: Innovt.Cloud.AWS.Configuration.DefaultAwsConfiguration
  commentId: T:Innovt.Cloud.AWS.Configuration.DefaultAwsConfiguration
  href: Innovt.Cloud.AWS.Configuration.DefaultAwsConfiguration.html
  name: DefaultAwsConfiguration
  nameWithType: DefaultAwsConfiguration
  fullName: Innovt.Cloud.AWS.Configuration.DefaultAwsConfiguration
- uid: Innovt.Cloud.AWS.Configuration.IAssumeRoleAwsConfiguration
  commentId: T:Innovt.Cloud.AWS.Configuration.IAssumeRoleAwsConfiguration
  parent: Innovt.Cloud.AWS.Configuration
  href: Innovt.Cloud.AWS.Configuration.IAssumeRoleAwsConfiguration.html
  name: IAssumeRoleAwsConfiguration
  nameWithType: IAssumeRoleAwsConfiguration
  fullName: Innovt.Cloud.AWS.Configuration.IAssumeRoleAwsConfiguration
- uid: Innovt.Cloud.AWS.Configuration.IAwsConfiguration
  commentId: T:Innovt.Cloud.AWS.Configuration.IAwsConfiguration
  parent: Innovt.Cloud.AWS.Configuration
  href: Innovt.Cloud.AWS.Configuration.IAwsConfiguration.html
  name: IAwsConfiguration
  nameWithType: IAwsConfiguration
  fullName: Innovt.Cloud.AWS.Configuration.IAwsConfiguration
- uid: Innovt.Cloud.AWS.Configuration
  commentId: N:Innovt.Cloud.AWS.Configuration
  href: Innovt.html
  name: Innovt.Cloud.AWS.Configuration
  nameWithType: Innovt.Cloud.AWS.Configuration
  fullName: Innovt.Cloud.AWS.Configuration
  spec.csharp:
  - uid: Innovt
    name: Innovt
    href: Innovt.html
  - name: .
  - uid: Innovt.Cloud
    name: Cloud
    href: Innovt.Cloud.html
  - name: .
  - uid: Innovt.Cloud.AWS
    name: AWS
    href: Innovt.Cloud.AWS.html
  - name: .
  - uid: Innovt.Cloud.AWS.Configuration
    name: Configuration
    href: Innovt.Cloud.AWS.Configuration.html
  spec.vb:
  - uid: Innovt
    name: Innovt
    href: Innovt.html
  - name: .
  - uid: Innovt.Cloud
    name: Cloud
    href: Innovt.Cloud.html
  - name: .
  - uid: Innovt.Cloud.AWS
    name: AWS
    href: Innovt.Cloud.AWS.html
  - name: .
  - uid: Innovt.Cloud.AWS.Configuration
    name: Configuration
    href: Innovt.Cloud.AWS.Configuration.html
