### YamlMime:ManagedReference
items:
- uid: Innovt.AspNetCore.Application.Tests.ViewModels
  commentId: N:Innovt.AspNetCore.Application.Tests.ViewModels
  id: Innovt.AspNetCore.Application.Tests.ViewModels
  children:
  - Innovt.AspNetCore.Application.Tests.ViewModels.AddUserViewModel
  langs:
  - csharp
  - vb
  name: Innovt.AspNetCore.Application.Tests.ViewModels
  nameWithType: Innovt.AspNetCore.Application.Tests.ViewModels
  fullName: Innovt.AspNetCore.Application.Tests.ViewModels
  type: Namespace
  assemblies:
  - Innovt.AspNetCore.Application.Tests
references:
- uid: Innovt.AspNetCore.Application.Tests.ViewModels.AddUserViewModel
  commentId: T:Innovt.AspNetCore.Application.Tests.ViewModels.AddUserViewModel
  parent: Innovt.AspNetCore.Application.Tests.ViewModels
  href: Innovt.AspNetCore.Application.Tests.ViewModels.AddUserViewModel.html
  name: AddUserViewModel
  nameWithType: AddUserViewModel
  fullName: Innovt.AspNetCore.Application.Tests.ViewModels.AddUserViewModel
- uid: Innovt.AspNetCore.Application.Tests.ViewModels
  commentId: N:Innovt.AspNetCore.Application.Tests.ViewModels
  href: Innovt.html
  name: Innovt.AspNetCore.Application.Tests.ViewModels
  nameWithType: Innovt.AspNetCore.Application.Tests.ViewModels
  fullName: Innovt.AspNetCore.Application.Tests.ViewModels
  spec.csharp:
  - uid: Innovt
    name: Innovt
    href: Innovt.html
  - name: .
  - uid: Innovt.AspNetCore
    name: AspNetCore
    href: Innovt.AspNetCore.html
  - name: .
  - uid: Innovt.AspNetCore.Application
    name: Application
    href: Innovt.AspNetCore.Application.html
  - name: .
  - uid: Innovt.AspNetCore.Application.Tests
    name: Tests
    href: Innovt.AspNetCore.Application.Tests.html
  - name: .
  - uid: Innovt.AspNetCore.Application.Tests.ViewModels
    name: ViewModels
    href: Innovt.AspNetCore.Application.Tests.ViewModels.html
  spec.vb:
  - uid: Innovt
    name: Innovt
    href: Innovt.html
  - name: .
  - uid: Innovt.AspNetCore
    name: AspNetCore
    href: Innovt.AspNetCore.html
  - name: .
  - uid: Innovt.AspNetCore.Application
    name: Application
    href: Innovt.AspNetCore.Application.html
  - name: .
  - uid: Innovt.AspNetCore.Application.Tests
    name: Tests
    href: Innovt.AspNetCore.Application.Tests.html
  - name: .
  - uid: Innovt.AspNetCore.Application.Tests.ViewModels
    name: ViewModels
    href: Innovt.AspNetCore.Application.Tests.ViewModels.html
